[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/smm/order"
  to = "https://my.smmgen.com/api/v2"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
